name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build_and_publish:

    runs-on: ubuntu-latest


    env:
      IMAGE_NAME: ${{ secrets.DOCKERHUB_USERNAME }}/dm_structure_apache_airflow:$(date +%s)

    steps:


    - name: Login to Docker Hub
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}


    - name: Configurar variável de saída
      id: my_step
      run: echo "::set-output name=MINHA_VARIAVEL::valor_da_variavel"


    - uses: actions/checkout@v3
    - name: Build the Docker image
      run: |
        docker build -t $IMAGE_NAME .
        docker push $IMAGE_NAME