name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build_and_publish:

    runs-on: self-hosted


    steps:

    - uses: actions/checkout@v2
    - name: docker images
      run: docker images